### PR TITLE
add default exports for sketch sub modules

### PR DESCRIPTION
**Pull request by chpio**
not sure if that's the best way of adding sub-modules, i tried adding `declare module` definitions to the index.d.ts file, but without success.

https://github.com/qjebbs/sketch.d.ts/issues/3

### CODE REVIEW

**Comment by qjebbs** [comment]
Sorry, I don't know what is this PR for.

If Sketch is not providing:
```
sketchAsync = require('sketchAsync')
sketchDataSupplier = require('sketchDataSupplier')
```
What can we do in the definition side?

PS: Sketch is providing:
```ts
// Or, require without UI, Settings, DataSupplier, Async,
var sketchDom: SketchDom = require('sketch/dom');
// and require others according to your needs
var async: Async = require('sketch/async');
var DataSupplier: DataSupplier = require('sketch/data-supplier');
var UI: UI = require('sketch/ui');
var Settings: Settings = require('sketch/settings');
```

**Comment by chpio** [comment]
> PS: Sketch is providing:

yeah, and with this you can have:

```ts
import sketchDom from "sketch/dom";
import sketchAsync from "sketch/async";
// etc
```

**Comment by qjebbs** [comment]
Good point, I didn't realize it can be improved in this way.

But test with your definition:

```ts
import sketchDom from "sketch/dom";
export function run() {
    console.log(
        sketchDom.version()
    )
}
```
Compiled with webpack:
```js
run=function(){console.log(n.default.version())}}

//full
(function(){var e=function(e){var t={};function r(n){if(t[n])return t[n].exports;var o=t[n]={i:n,l:!1,exports:{}};return e[n].call(o.exports,o,o.exports,r),o.l=!0,o.exports}return r.m=e,r.c=t,r.d=function(e,t,n){r.o(e,t)||Object.defineProperty(e,t,{enumerable:!0,get:n})},r.r=function(e){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(e,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(e,"__esModule",{value:!0})},r.t=function(e,t){if(1&t&&(e=r(e)),8&t)return e;if(4&t&&"object"==typeof e&&e&&e.__esModule)return e;var n=Object.create(null);if(r.r(n),Object.defineProperty(n,"default",{enumerable:!0,value:e}),2&t&&"string"!=typeof e)for(var o in e)r.d(n,o,function(t){return e[t]}.bind(null,o));return n},r.n=function(e){var t=e&&e.__esModule?function(){return e.default}:function(){return e};return r.d(t,"a",t),t},r.o=function(e,t){return Object.prototype.hasOwnProperty.call(e,t)},r.p="",r(r.s=0)}([function(e,t,r){"use strict";Object.defineProperty(t,"__esModule",{value:!0});const n=r(1);t.run=function(){console.log(n.default.version())}},function(e,t){e.exports=require("sketch/dom")}]);;return e})()
```

Why there is a `default`? how to fix it? (the compiled code cannot run: TypeError: n.default.version is not a function.)

**Comment by chpio** [comment]
wtf?

```ts
import async from "sketch/async";

const wakeLock = async.createFiber();
```

seem to work without a problem (with webpack; you're using the ts compiler directly?!)

but this fails for me as well:

```ts
import sketchDom from "sketch/dom";

console.log(sketchDom.version());
```

-----

> Why there is a default?

that's because the es6 modules import/export system is a little bit different. the old overriding the exported object `module.exports = function myFoo() {};` had some problems, like breaking hard in the case of circular dependencies. the new es6 modules never overrides the "root" `module.exports` object, thus they needed to move the "root" export **into** the `module.exports` object, it's called `default`. There's usually compatibility for the old format in es6 module loaders (they flag es6 exports with an `__esModule = true` and handle imports without that flag as the old format).

```ts
// the `default` export from "somemodule" is now put into the `foo` variable
import foo from "somemodule";

// the `foo` export from "somemodule" is now put into the `foo` variable
import {foo} from "somemodule";

```

it seems like that
* the sketch exports are somehow broken (like setting the `__esModule` flag but not using the es6 module format)
* or/and they are exporting a different scheme (for some) modules

**Comment by chpio** [comment]
i probably should close this. There's not much advantage in having native support for all the sub modules, if we are already able to import the root module (`import sketch from "sketch";`) and have access to the functionality of all the sub modules.

**Comment by qjebbs** [comment]
Actually, `import sketch from "sketch"` also leads to `default` here.

**Pull request closed without merging**
